# Data Analysis

## data collection - website
                - company
                - surveys
                - Likes/dislikes/share/clicks
                - google
                

## data clean

### data transform into usable format

### Data Filtering

### Data Study/Understanding/Exploration

 -ASSUMPTION
-Observations
-Inference
-Conclusion

In [1]:
import numpy as np

In [2]:
l=[1,2,3]
a=np.array(l)

In [3]:
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [4]:
a.ndim

1

In [5]:
l1=[[1,2,3],[4,5,6]]
b=np.array(l1)

b.ndim

2

In [6]:
l2=[[[1,2,3],
   [4,5,6],
   [7,8,9]]]
c=np.array(l2)
c.ndim


3

In [7]:
l2=[[[[1,2,3],
   [4,5,6],
   [7,8,9]]]]
c=np.array(l2)
c.ndim

4

In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

In [10]:
a.dtype

dtype('int32')

In [11]:
c=np.array([[1,2,3,4],
           [5,6,7,8]],dtype=float)

In [12]:
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [13]:
a=np.zeros((4,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
f=np.ones((2,3))
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
n=np.array([[[[1,2,3]]]])
n.shape

(1, 1, 1, 3)

In [16]:
g=np.full((3,4,2),'hi')
g

array([[['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi']],

       [['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi']],

       [['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi']]], dtype='<U2')

In [17]:
x=34
np.full((5,2),float(x),dtype=complex)


array([[34.+0.j, 34.+0.j],
       [34.+0.j, 34.+0.j],
       [34.+0.j, 34.+0.j],
       [34.+0.j, 34.+0.j],
       [34.+0.j, 34.+0.j]])

In [18]:
h=np.arange(3,10,2)
h

array([3, 5, 7, 9])

In [19]:
np.linspace(2,10,3)

array([ 2.,  6., 10.])

In [20]:
np.linspace(2,15,5)

array([ 2.  ,  5.25,  8.5 , 11.75, 15.  ])

In [21]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
a.shape

(4, 3)

In [23]:
a.size
a1=a.reshape((2,2,3))
a1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
a.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
at=a.T
at

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
g

array([[['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi']],

       [['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi']],

       [['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi'],
        ['hi', 'hi']]], dtype='<U2')

In [27]:
g.T.shape

(2, 4, 3)

### Indexing in Numpy

In [28]:
c1=np.array([[1,2,3,4],[5,6,7,8],[11,45,61,23]])
c1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 45, 61, 23]])

In [29]:
#Integer array indexing
#Boolean array indexing

In [30]:
c1[[0,1],[2,1]]

array([3, 6])

In [31]:
#Boolean Array Indexing

In [32]:
c1[c1%2==0]

array([2, 4, 6, 8])

In [33]:
c1[c1>6]

array([ 7,  8, 11, 45, 61, 23])

### Slicing

In [34]:
c1[1:,1:3]

array([[ 6,  7],
       [45, 61]])

In [35]:
c1[1::,::2]

array([[ 5,  7],
       [11, 61]])

In [36]:
c1[1:,2:3]

array([[ 7],
       [61]])

In [37]:
l=[11,2,9,0]
a=np.array(l)

In [38]:
print([i+5 for i in [1,2,3,4] ])

[6, 7, 8, 9]


In [39]:
print(list(np.array([11,2,9,0])+5))

[16, 7, 14, 5]


In [40]:
print(list(np.array([11,2,9,0])-1))

[10, 1, 8, -1]


In [41]:
print(list(np.array([11,2,9,0])*2))

[22, 4, 18, 0]


In [42]:
print(list(np.array([11,2,9,0])/2))

[5.5, 1.0, 4.5, 0.0]


In [43]:
print(list(np.array([11,2,9,0])**2))

[121, 4, 81, 0]


In [44]:
print(list(np.array([11,2,9,0])//2))

[5, 1, 4, 0]


In [45]:
a

array([11,  2,  9,  0])

In [46]:
b=np.array([1,5,2,7])
b

array([1, 5, 2, 7])

# Element Wise Arithemtic operation 

In [47]:
print(a+b)

[12  7 11  7]


In [48]:
print(a-b)

[10 -3  7 -7]


In [49]:
print(a*b)

[11 10 18  0]


In [50]:
print(a/b)

[11.   0.4  4.5  0. ]


In [51]:
print(a//b)

[11  0  4  0]


In [52]:
print(a%b)

[0 2 1 0]


In [53]:
print(a**b)

[11 32 81  0]


In [54]:
###Matrix Multiplication
###Dot Multiplication

In [55]:
l1=np.array([[1,2],[4,5],[3,6]])
l2=np.array([[7,8,9],[10,11,12]])

In [56]:
print(l1.shape)
print(l2.shape)

(3, 2)
(2, 3)


In [57]:
c1=l1.dot(l2)
c1

array([[27, 30, 33],
       [78, 87, 96],
       [81, 90, 99]])

In [58]:
print(l2.dot(l1))

[[ 66 108]
 [ 90 147]]


In [60]:
d=np.array([[11,2,3,4],
           [5,6,9,8],
           [3,7,1,9]])
d

array([[11,  2,  3,  4],
       [ 5,  6,  9,  8],
       [ 3,  7,  1,  9]])

In [62]:
d.sum()

68

In [63]:
d.sum(axis=0)

array([19, 15, 13, 21])

In [64]:
d.sum(axis=1)

array([20, 28, 20])

In [66]:
d.max()

11

In [68]:
d.max(axis=0)

array([11,  7,  9,  9])

In [69]:
d.min(axis=1)

array([2, 5, 1])

In [70]:
d.mean(axis=0)

array([6.33333333, 5.        , 4.33333333, 7.        ])

In [71]:
d.cumsum(axis=0)

array([[11,  2,  3,  4],
       [16,  8, 12, 12],
       [19, 15, 13, 21]])

In [72]:
d.cumsum(axis=1)

array([[11, 13, 16, 20],
       [ 5, 11, 20, 28],
       [ 3, 10, 11, 20]])

In [73]:
d.cumprod(axis=0)

array([[ 11,   2,   3,   4],
       [ 55,  12,  27,  32],
       [165,  84,  27, 288]])

In [74]:
a

array([11,  2,  9,  0])

In [75]:
np.sin(a)

array([-0.99999021,  0.90929743,  0.41211849,  0.        ])

In [76]:
np.cos(a)

array([ 0.0044257 , -0.41614684, -0.91113026,  1.        ])

In [77]:
np.tan(a)

array([-225.95084645,   -2.18503986,   -0.45231566,    0.        ])

In [78]:
np.log10(a)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_6156\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([1.04139269, 0.30103   , 0.95424251,       -inf])

In [79]:
np.sqrt(a)

array([3.31662479, 1.41421356, 3.        , 0.        ])

In [80]:
np.ceil(a)

array([11.,  2.,  9.,  0.])

In [81]:
np.floor(a)

array([11.,  2.,  9.,  0.])

In [82]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [83]:
len(dir(np))

596

In [84]:
np.sort(a)

array([ 0,  2,  9, 11])